export const GET_OLD_SESSIONS_REQUESTED = "GET_OLD_SESSIONS_REQUESTED";
export const GET_OLD_SESSIONS_SUCCESS = "GET_OLD_SESSIONS_SUCCESS";
export const GET_OLD_SESSIONS_FAILED = "GET_OLD_SESSIONS_FAILED";

export const ADD_NEW_SESSION_SUCCESS = "ADD_NEW_SESSION_SUCCESS";
export const ADD_NEW_SESSION_FAILED = "ADD_NEW_SESSION_FAILED";

export const START_TIMER = "START_TIMER";
export const RESET_TIMER = "RESET_TIMER";
export const PAUSE_TIMER = "PAUSE_TIMER";
